import {
  createRepositoryIndex,
  parseRepositoryIndex,
  serializeRepositoryIndex,
  upsertRepositorySolution,
} from "./metadata-index";

import {
  generatePatternIndex,
} from "./pattern-index";

import {
  generateTopicIndex,
} from "./topic-index";

import {
  generatePortfolioReadme,
} from "./portfolio-readme-generator";

import {
  generateActivityHeatmap,
} from "./activity-heatmap-generator";

import type {
  RepositoryIndex,
  RepositorySolution,
} from "./types";

/**
 * Result generated by the Repository Engine.
 */
export interface RepositoryEngineResult {

  /**
   * Updated metadata index.
   */
  index: RepositoryIndex;

  /**
   * Files that should be written to GitHub.
   */
  files: {
    path: string;
    content: string;
  }[];
}

/**
 * Generates repository organization artifacts
 * from a coding solution.
 */
export class RepositoryEngine {

  private index: RepositoryIndex;

  constructor(
    index?: RepositoryIndex,
  ) {
    this.index =
      index ??
      createRepositoryIndex();
  }

  /**
   * Creates a Repository Engine from
   * an existing repository index.
   */
  static fromIndex(
    content: string | null,
  ): RepositoryEngine {
    return new RepositoryEngine(
      parseRepositoryIndex(content),
    );
  }

  /**
   * Registers a solution and generates
   * the required repository indexes.
   */
  process(
    solution: RepositorySolution,
  ): RepositoryEngineResult {

    this.index =
      upsertRepositorySolution(
        this.index,
        solution,
      );

const files = [
  {
    path: ".codevault/index.json",
    content:
      serializeRepositoryIndex(
        this.index,
      ),
  },

  {
    path: ".codevault/activity.svg",
    content:
      generateActivityHeatmap(
        this.index,
      ),
  },

  ...this.generatePatternFiles(),

  ...this.generateTopicFiles(),

  {
    path: "README.md",
    content:
      generatePortfolioReadme(
        this.index,
      ),
  },
];

    return {
      index: this.index,
      files,
    };
  }

  /**
   * Generates pattern Markdown files.
   */
  private generatePatternFiles() {

    const patterns =
      this.collectPatterns();

    return patterns.map(
      (pattern) => ({
        path:
          `patterns/${pattern}.md`,

        content:
          generatePatternIndex(
            pattern,
            this.index.solutions,
          ),
      }),
    );
  }

  /**
   * Generates topic Markdown files.
   */
  private generateTopicFiles() {

    const topics =
      this.collectTopics();

    return topics.map(
      (topic) => ({
        path:
          `topics/${topic}.md`,

        content:
          generateTopicIndex(
            topic,
            this.index.solutions,
          ),
      }),
    );
  }

  /**
   * Collects unique patterns.
   */
  private collectPatterns(): string[] {

    return [
      ...new Set(
        this.index.solutions.flatMap(
          (solution) =>
            solution.metadata.patterns ?? [],
        ),
      ),
    ].sort();
  }

  /**
   * Collects unique topics.
   */
  private collectTopics(): string[] {

    return [
      ...new Set(
        this.index.solutions.flatMap(
          (solution) =>
            solution.metadata.topics ?? [],
        ),
      ),
    ].sort();
  }
}