const STORAGE_KEY =
  "codevault.sync.fingerprints";

const MAX_FINGERPRINTS = 1000;

/**
 * Fingerprint schema version.
 *
 * Incrementing this value invalidates fingerprints
 * generated by older fingerprint formats.
 */
const FINGERPRINT_VERSION = "v2";

/**
 * Generates a deterministic fingerprint for a solution.
 *
 * A solution is uniquely identified by:
 *
 * Platform
 * + Problem Slug
 * + Programming Language
 * + Source Code
 *
 * This is important because the same problem can be
 * solved and synchronized in multiple languages.
 *
 * Example:
 *
 * LeetCode | two-sum | Java   | source
 * LeetCode | two-sum | Python | source
 *
 * must produce different fingerprints.
 */
export async function generateFingerprint(
  platform: string,
  slug: string,
  language: string,
  sourceCode: string,
): Promise<string> {
  /*
   * Normalize metadata so equivalent values produce
   * the same fingerprint.
   */
  const normalizedPlatform =
    platform.trim().toLowerCase();

  const normalizedSlug =
    slug.trim().toLowerCase();

  const normalizedLanguage =
    language.trim().toLowerCase();

  /*
   * Source code is intentionally NOT lowercased or
   * otherwise modified because source code is
   * case-sensitive.
   */
  const normalizedSourceCode =
    sourceCode.trim();

  /*
   * Fail fast if required fingerprint components
   * are missing.
   */
  if (!normalizedPlatform) {
    throw new Error(
      "Cannot generate fingerprint: platform is missing.",
    );
  }

  if (!normalizedSlug) {
    throw new Error(
      "Cannot generate fingerprint: problem slug is missing.",
    );
  }

  if (!normalizedLanguage) {
    throw new Error(
      "Cannot generate fingerprint: programming language is missing.",
    );
  }

  if (!normalizedSourceCode) {
    throw new Error(
      "Cannot generate fingerprint: source code is empty.",
    );
  }

  /*
   * Include the schema version so fingerprints from
   * older formats cannot collide with the new format.
   */
  const fingerprintInput =
    [
      FINGERPRINT_VERSION,
      normalizedPlatform,
      normalizedSlug,
      normalizedLanguage,
      normalizedSourceCode,
    ].join("|");

  const encoder =
    new TextEncoder();

  const data =
    encoder.encode(
      fingerprintInput,
    );

  const hash =
    await crypto.subtle.digest(
      "SHA-256",
      data,
    );

  return Array.from(
    new Uint8Array(hash),
  )
    .map((byte) =>
      byte
        .toString(16)
        .padStart(2, "0"),
    )
    .join("");
}

/**
 * Loads all synchronized fingerprints.
 */
async function loadFingerprints(): Promise<
  Set<string>
> {
  const fingerprints =
    await storage.getItem<string[]>(
      `local:${STORAGE_KEY}`,
    );

  return new Set(
    fingerprints ?? [],
  );
}

/**
 * Returns true when the fingerprint has already
 * been synchronized successfully.
 */
export async function isFingerprintSynced(
  fingerprint: string,
): Promise<boolean> {
  if (!fingerprint.trim()) {
    return false;
  }

  const fingerprints =
    await loadFingerprints();

  return fingerprints.has(
    fingerprint,
  );
}

/**
 * Saves a synchronized fingerprint.
 *
 * The fingerprint is saved only after GitHub
 * synchronization succeeds.
 */
export async function saveFingerprint(
  fingerprint: string,
): Promise<void> {
  if (!fingerprint.trim()) {
    throw new Error(
      "Cannot save an empty synchronization fingerprint.",
    );
  }

  const fingerprints =
    await loadFingerprints();

  fingerprints.add(
    fingerprint,
  );

  const values =
    Array.from(
      fingerprints,
    );

  /*
   * Keep only the newest MAX_FINGERPRINTS entries.
   *
   * Set insertion order is preserved by JavaScript,
   * so removing from the beginning removes the oldest
   * stored fingerprints.
   */
  if (
    values.length >
    MAX_FINGERPRINTS
  ) {
    values.splice(
      0,
      values.length -
        MAX_FINGERPRINTS,
    );
  }

  await storage.setItem(
    `local:${STORAGE_KEY}`,
    values,
  );
}

/**
 * Clears all synchronized fingerprints.
 *
 * Useful for development/testing when a complete
 * synchronization reset is required.
 */
export async function clearFingerprints(): Promise<void> {
  await storage.removeItem(
    `local:${STORAGE_KEY}`,
  );
}