# spring.application.name=backend

# github.client-id=Ov23lixqgD0bTqArz6iL
# github.client-secret=1b84fddd5330a0d1267e976c764e5c6e7c0e96cf
spring.application.name=backend

github.client-id=${GITHUB_CLIENT_ID}
github.client-secret=${GITHUB_CLIENT_SECRET}